---
- hosts: all
  become: true
  roles:
    - { role: mysql}
    - { role: misp}
    - { role: apache}

  vars:
    proxy_host: ""
    proxy_port: ""
    servername: "misp.local"
    mysql_root_old_pass: ""
    mysql_root_new_pass: "CHANGETHISHERE"
    mysql_misp_password: ""
    enable_auto_backup: "n"
    install_modules: "n"
